// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20200402040334_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.MovimientoFinanciero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CuentaBancariaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ValorConsignacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorRetiro")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CuentaBancariaId");

                    b.ToTable("MovimientoFinanciero");
                });

            modelBuilder.Entity("Domain.Entities.ServicioFinanciero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ServicioFinanciero");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ServicioFinanciero");
                });

            modelBuilder.Entity("Domain.Entities.CertificadoDeDepositoATermino", b =>
                {
                    b.HasBaseType("Domain.Entities.ServicioFinanciero");

                    b.Property<int>("DiasDeTermino")
                        .HasColumnType("int");

                    b.Property<bool>("TieneConsignacion")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("CertificadoDeDepositoATermino");
                });

            modelBuilder.Entity("Domain.Entities.CuentaAhorro", b =>
                {
                    b.HasBaseType("Domain.Entities.ServicioFinanciero");

                    b.HasDiscriminator().HasValue("CuentaAhorro");
                });

            modelBuilder.Entity("Domain.Entities.CuentaCorriente", b =>
                {
                    b.HasBaseType("Domain.Entities.ServicioFinanciero");

                    b.Property<decimal>("CupoDeSobregiro")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("tieneConsignaciones")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("CuentaCorriente");
                });

            modelBuilder.Entity("Domain.Entities.MovimientoFinanciero", b =>
                {
                    b.HasOne("Domain.Entities.ServicioFinanciero", "CuentaBancaria")
                        .WithMany("Movimientos")
                        .HasForeignKey("CuentaBancariaId");
                });
#pragma warning restore 612, 618
        }
    }
}
